apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: php-app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php
        image: edsola/php:0.0.1
        resources:
          limits:
            cpu: "20m"
            memory: "128Mi"
          requests:
            cpu: "20m"
            memory: "128Mi"
        ports:
        - containerPort: 80
